print("Masukkan Nama Anda : ")
nama = input()
print("Masukkan Umur Anda : ")
umur = input()
print()
alamat = input("Masukkan alamat anda : ")
print("Nama anda adalah "+nama)
print("Umur anda adalah "+umur)
print("Anda beralamat di "+alamat)